### ISSUE TITLE
Error while loading up

### ISSUE THREAD

**Issue by BluMasc** [DeflatedPickle/JustBiteTheDust#1]
got this error while loading the game:
Caught exception from justbitethedust (java.lang.IllegalArgumentException: The name justbitethedust:psi_nugget has been registered twice, for com.deflatedpickle.justbitethedust.items.ItemBase@35bc1511 and com.deflatedpickle.justbitethedust.items.ItemBase@36a81475.)

instance has over 140 mods

**Comment by DeflatedPickle** [comment]
Sorry for not commenting earlier, pretty sure you'll have stopped using this, but thank you for reporting it. It never occured to me to check if an material had already been registered.

I'm closing this as the mod is either dead or will be re-written, not sure.
